**1) Install/ Import the required Python Packages/ Libraries**

In [ ]:
#Import required python packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn import preprocessing
%matplotlib inline

**2) Mounting the Google Drive**

In [ ]:
# Mount the Google Drive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


**3) Read the Data file and check**

In [ ]:
# Read the Diabetes Data from .csv file and check the data shape (number of Rows and Columns)
#df = pd.read_csv('gdrive/My Drive/Indi_ML_Training/Training-Sessions/MLP-Session25-05-Jun-2021/train_ctrUa4K.csv')
df = pd.read_csv("gdrive/My Drive/SRM-MLP-Internship-2021/Projects/Classification/01-Loan-Status-Prediction/Data-Files/Loan_Status_Train_Preprocessed.csv")
print(df.shape)
df.head()

(614, 12)


Dependents  Education  ...  Self_Employed_Yes  Loan_Status
0    0.000000        0.0  ...                0.0            1
1    0.333333        0.0  ...                0.0            0
2    0.000000        0.0  ...                1.0            1
3    0.000000        1.0  ...                0.0            1
4    0.000000        0.0  ...                0.0            1

[5 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Dependents         614 non-null    float64
 1   Education          614 non-null    float64
 2   ApplicantIncome    614 non-null    float64
 3   CoapplicantIncome  614 non-null    float64
 4   LoanAmount         614 non-null    float64
 5   Loan_Amount_Term   614 non-null    float64
 6   Credit_History     614 non-null    float64
 7   Property_Area      614 non-null    float64
 8   Gender_Male        614 non-null    float64
 9   Married_Yes        614 non-null    float64
 10  Self_Employed_Yes  614 non-null    float64
 11  Loan_Status        614 non-null    int64  
dtypes: float64(11), int64(1)
memory usage: 57.7 KB


##**VII) Check the Test accuracy using appropriate algorithm and Holdout Method.**

##**Step-5: Slice X and y Values**

In [ ]:
X = df.drop(['Loan_Status'], axis = 1)
Y = df['Loan_Status']
X.head()

Dependents  Education  ...  Married_Yes  Self_Employed_Yes
0    0.000000        0.0  ...          0.0                0.0
1    0.333333        0.0  ...          1.0                0.0
2    0.000000        0.0  ...          1.0                1.0
3    0.000000        1.0  ...          1.0                0.0
4    0.000000        0.0  ...          0.0                0.0

[5 rows x 11 columns]

In [ ]:
Y.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

##**Step-6: Execute Train-Test-Split Command and Verify**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 66)

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(491, 11)
(491,)
(123, 11)
(123,)


##**Step-7: Learn the Data and Predict the dependent Variable values for the "X_test"data using "LogisticRegression()" algorithm**

In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel = LogisticRegression()
logmodel.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_pred = logmodel.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

##**Step-8: Calculate the Accuracy of the Model**

In [ ]:
accuracy_lr = logmodel.score(X_test, y_test)
print("Accuracy of Logistic Regression on test set:",accuracy_lr)

Accuracy of Logistic Regression on test set: 0.8292682926829268


##**Step-9: Display the Confusion Matrix and Classification Report of the Model**

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  

[[15 20]
 [ 1 87]]
              precision    recall  f1-score   support

           0       0.94      0.43      0.59        35
           1       0.81      0.99      0.89        88

    accuracy                           0.83       123
   macro avg       0.88      0.71      0.74       123
weighted avg       0.85      0.83      0.81       123



##**IX) Check for Multi-collinearity and find out the new accuracy as required**

###**Checking for MultiCollinearity**

VIF starts at 1 and has no upper limit

VIF = 1, no correlation between the independent variable and the other variables

VIF exceeding 5 or 10 indicates high multicollinearity between this independent variable and the others

In [ ]:
# Import library for VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
calc_vif(X)

variables       VIF
0          Dependents  1.791746
1           Education  1.306583
2     ApplicantIncome  2.813280
3   CoapplicantIncome  1.481231
4          LoanAmount  6.176425
5    Loan_Amount_Term  9.895693
6      Credit_History  6.016383
7       Property_Area  2.568846
8         Gender_Male  5.982523
9         Married_Yes  3.652339
10  Self_Employed_Yes  1.176282

In [ ]:
X.shape

(614, 11)

In [ ]:
X1= X.drop(['Loan_Amount_Term'], axis=1, inplace=False)

In [ ]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Dependents         614 non-null    float64
 1   Education          614 non-null    float64
 2   ApplicantIncome    614 non-null    float64
 3   CoapplicantIncome  614 non-null    float64
 4   LoanAmount         614 non-null    float64
 5   Credit_History     614 non-null    float64
 6   Property_Area      614 non-null    float64
 7   Gender_Male        614 non-null    float64
 8   Married_Yes        614 non-null    float64
 9   Self_Employed_Yes  614 non-null    float64
dtypes: float64(10)
memory usage: 48.1 KB


In [ ]:
calc_vif(X1)

variables       VIF
0         Dependents  1.790141
1          Education  1.276369
2    ApplicantIncome  2.804867
3  CoapplicantIncome  1.479645
4         LoanAmount  5.626065
5     Credit_History  4.389408
6      Property_Area  2.393587
7        Gender_Male  5.398082
8        Married_Yes  3.646531
9  Self_Employed_Yes  1.175003

In [ ]:
from sklearn.model_selection import train_test_split
X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y, test_size = 0.2, random_state = 66)

In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel2 = LogisticRegression()
logmodel2.fit(X1_train, Y1_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#predictions
predictions1 = logmodel2.predict(X1_test)

In [ ]:
print(confusion_matrix(Y1_test, predictions1))
print(classification_report(Y1_test,predictions1))

[[15 20]
 [ 1 87]]
              precision    recall  f1-score   support

           0       0.94      0.43      0.59        35
           1       0.81      0.99      0.89        88

    accuracy                           0.83       123
   macro avg       0.88      0.71      0.74       123
weighted avg       0.85      0.83      0.81       123



**Observation: After removal of the column " Loan_Amount_Term" the model gives the accuracy of 83%**

**Decision: We will not remove the column "Loan_Amount_Term"**

##**X) Check for Outliers and handle them accordingly**

###**Outliers Detection**

In [ ]:
df1=df

In [ ]:
df1.head()

Dependents  Education  ...  Self_Employed_Yes  Loan_Status
0    0.000000        0.0  ...                0.0            1
1    0.333333        0.0  ...                0.0            0
2    0.000000        0.0  ...                1.0            1
3    0.000000        1.0  ...                0.0            1
4    0.000000        0.0  ...                0.0            1

[5 rows x 12 columns]

In [ ]:
from scipy import stats
import numpy as np
z = np.abs(stats.zscore(df1))
print(z[:9])

[[7.37806323e-01 5.28362249e-01 7.29908229e-02 5.54487330e-01
  3.02759186e-01 2.73231296e-01 4.11732692e-01 1.22329839e+00
  4.72342640e-01 1.37208932e+00 3.92600737e-01 6.74519313e-01]
 [2.53469568e-01 5.28362249e-01 1.34411954e-01 3.87315485e-02
  2.07648344e-01 2.73231296e-01 4.11732692e-01 1.31851281e+00
  4.72342640e-01 7.28815525e-01 3.92600737e-01 1.48253724e+00]
 [7.37806323e-01 5.28362249e-01 3.93747337e-01 5.54487330e-01
  9.44757367e-01 2.73231296e-01 4.11732692e-01 1.22329839e+00
  4.72342640e-01 7.28815525e-01 2.54711697e+00 6.74519313e-01]
 [7.37806323e-01 1.89264089e+00 4.62062470e-01 2.51979602e-01
  3.02759186e-01 2.73231296e-01 4.11732692e-01 1.22329839e+00
  4.72342640e-01 7.28815525e-01 3.92600737e-01 6.74519313e-01]
 [7.37806323e-01 5.28362249e-01 9.77284368e-02 5.54487330e-01
  5.30932264e-02 2.73231296e-01 4.11732692e-01 1.22329839e+00
  4.72342640e-01 1.37208932e+00 3.92600737e-01 6.74519313e-01]
 [1.24474546e+00 5.28362249e-01 2.21831139e-03 8.80599712e-01
  1

In [ ]:
z.shape

(614, 12)

In [ ]:
df2 = df1

In [ ]:
threshold = 3
print(np.where(z > 3))

(array([  9,  14,  68,  94, 126, 130, 133, 155, 155, 171, 171, 177, 177,
       183, 185, 242, 262, 278, 308, 313, 333, 333, 369, 402, 409, 417,
       432, 443, 487, 495, 497, 506, 523, 525, 546, 561, 575, 581, 585,
       600, 604]), array([3, 5, 5, 5, 2, 4, 5, 2, 4, 2, 4, 3, 4, 2, 2, 5, 5, 4, 4, 5, 2, 4,
       4, 3, 2, 3, 4, 2, 4, 5, 5, 4, 4, 4, 5, 4, 5, 3, 5, 3, 4]))


In [ ]:
df2 = df2[(z < 3).all(axis=1)]

In [ ]:
df2.shape

(577, 12)

In [ ]:
X3 = df.drop(['Loan_Status'], axis = 1)
Y3 = df['Loan_Status']
X3.head()

Dependents  Education  ...  Married_Yes  Self_Employed_Yes
0    0.000000        0.0  ...          0.0                0.0
1    0.333333        0.0  ...          1.0                0.0
2    0.000000        0.0  ...          1.0                1.0
3    0.000000        1.0  ...          1.0                0.0
4    0.000000        0.0  ...          0.0                0.0

[5 rows x 11 columns]

In [ ]:
columnNames = ['Dependents', 'Education', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Gender_Male', 'Married_Yes', 'Self_Employed_Yes']

In [ ]:
min_max_scaler_object = preprocessing.MinMaxScaler()
X3A = min_max_scaler_object.fit_transform(X3)
X3A = pd.DataFrame(X3A , columns = columnNames)
X3A.head()

Dependents  Education  ...  Married_Yes  Self_Employed_Yes
0    0.000000        0.0  ...          0.0                0.0
1    0.333333        0.0  ...          1.0                0.0
2    0.000000        0.0  ...          1.0                1.0
3    0.000000        1.0  ...          1.0                0.0
4    0.000000        0.0  ...          0.0                0.0

[5 rows x 11 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X3_train, X3_test, Y3_train, Y3_test = train_test_split(X3A, Y3, test_size = 0.2, random_state = 66)

In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel2 = LogisticRegression()
logmodel2.fit(X3_train, Y3_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#predictions
predictions4 = logmodel2.predict(X3_test)

In [ ]:
print(confusion_matrix(Y3_test, predictions4))
print(classification_report(Y3_test,predictions4))

[[15 20]
 [ 1 87]]
              precision    recall  f1-score   support

           0       0.94      0.43      0.59        35
           1       0.81      0.99      0.89        88

    accuracy                           0.83       123
   macro avg       0.88      0.71      0.74       123
weighted avg       0.85      0.83      0.81       123



**Observation: After Outliers removal we get the accuracy of 83%**

**Decision: We will not remove the Outliers Data.**

##**XI) Check for Feature Selection/ Extraction and verify the accuracy**

###**Using Correlation Coefficient Method**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Dependents         614 non-null    float64
 1   Education          614 non-null    float64
 2   ApplicantIncome    614 non-null    float64
 3   CoapplicantIncome  614 non-null    float64
 4   LoanAmount         614 non-null    float64
 5   Loan_Amount_Term   614 non-null    float64
 6   Credit_History     614 non-null    float64
 7   Property_Area      614 non-null    float64
 8   Gender_Male        614 non-null    float64
 9   Married_Yes        614 non-null    float64
 10  Self_Employed_Yes  614 non-null    float64
 11  Loan_Status        614 non-null    int64  
dtypes: float64(11), int64(1)
memory usage: 57.7 KB


In [ ]:
cor=df.corr()
cor

Dependents  Education  ...  Self_Employed_Yes  Loan_Status
Dependents           1.000000   0.055752  ...           0.056798     0.010118
Education            0.055752   1.000000  ...          -0.010383    -0.085884
ApplicantIncome      0.118202  -0.140760  ...           0.127180    -0.004710
CoapplicantIncome    0.030430  -0.062290  ...          -0.016100    -0.059187
LoanAmount           0.163017  -0.169436  ...           0.114971    -0.031808
Loan_Amount_Term    -0.103864  -0.073928  ...          -0.033739    -0.022549
Credit_History      -0.040160  -0.073658  ...          -0.001550     0.540556
Property_Area       -0.000244  -0.065243  ...          -0.030860     0.032112
Gender_Male          0.172914   0.045364  ...          -0.000525     0.017987
Married_Yes          0.334216   0.012304  ...           0.004489     0.091478
Self_Employed_Yes    0.056798  -0.010383  ...           1.000000    -0.003700
Loan_Status          0.010118  -0.085884  ...          -0.003700     1.000000

[12 rows x 12 columns]

In [ ]:
threshold=0.5
a = abs(cor['Loan_Status'])
a

Dependents           0.010118
Education            0.085884
ApplicantIncome      0.004710
CoapplicantIncome    0.059187
LoanAmount           0.031808
Loan_Amount_Term     0.022549
Credit_History       0.540556
Property_Area        0.032112
Gender_Male          0.017987
Married_Yes          0.091478
Self_Employed_Yes    0.003700
Loan_Status          1.000000
Name: Loan_Status, dtype: float64

In [ ]:
result = a[a>0.5]
result

Credit_History    0.540556
Loan_Status       1.000000
Name: Loan_Status, dtype: float64

In [ ]:
df4=df.drop(['Dependents', 'Education', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Property_Area', 'Gender_Male', 'Self_Employed_Yes', 'Married_Yes'], axis=1)

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Credit_History  614 non-null    float64
 1   Loan_Status     614 non-null    int64  
dtypes: float64(1), int64(1)
memory usage: 9.7 KB


In [ ]:
X5 = df4.drop(['Loan_Status'], axis = 1)
Y5 = df4['Loan_Status']
X5.head()

Credit_History
0             1.0
1             1.0
2             1.0
3             1.0
4             1.0

In [ ]:
Y5.head()

0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X5_train, X5_test, Y5_train, Y5_test = train_test_split(X5, Y5, test_size = 0.2, random_state = 66)

In [ ]:
print(X5_train.shape)
print(Y5_train.shape)
print(X5_test.shape)
print(Y5_test.shape)

(491, 1)
(491,)
(123, 1)
(123,)


In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel2 = LogisticRegression()
logmodel2.fit(X5_train, Y5_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#predictions
predictions5 = logmodel2.predict(X5_test)

In [ ]:
print(confusion_matrix(Y5_test, predictions5))
print(classification_report(Y5_test,predictions5))

[[15 20]
 [ 1 87]]
              precision    recall  f1-score   support

           0       0.94      0.43      0.59        35
           1       0.81      0.99      0.89        88

    accuracy                           0.83       123
   macro avg       0.88      0.71      0.74       123
weighted avg       0.85      0.83      0.81       123



**Observation: Even by having only one independent variable column "Credit_History", we get the accuracy of 83%**

###**Decision: We can try all Classifiers with "Credit_History" as the only Independent Variable Data**

###**Applying PCA**

In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_train6 = pca.fit_transform(X_train)
X_test6 = pca.transform(X_test)
print(X_train6.shape)
print(X_test6.shape)
print(X_train6[:5])
print(Y[:5])

(491, 2)
(123, 2)
[[ 0.94555733  0.4468858 ]
 [-0.3749544  -0.01700197]
 [-0.48621786 -0.17900379]
 [-0.28982769 -0.26693192]
 [ 0.99356189 -0.42487859]]
0    1
1    0
2    1
3    1
4    1
Name: Loan_Status, dtype: int64


In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel2 = LogisticRegression()
logmodel2.fit(X_train6, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#predictions
predictions6 = logmodel2.predict(X_test6)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions6))  
print(classification_report(y_test,predictions6))  

[[ 2 33]
 [ 1 87]]
              precision    recall  f1-score   support

           0       0.67      0.06      0.11        35
           1       0.72      0.99      0.84        88

    accuracy                           0.72       123
   macro avg       0.70      0.52      0.47       123
weighted avg       0.71      0.72      0.63       123



**Observation: By using the PCA Method, we get the accuracy of 83%**

###**Decision: We will not use the PCA Method for reducing the features**

###**Using LDA**

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)
X_train7 = lda.fit_transform(X_train, y_train)
X_test7 = lda.transform(X_test)
print(X_train7[:5])
print()
print(X_test7[:5])

[[0.06563705]
 [0.68275983]
 [0.88499865]
 [0.73591284]
 [0.55129086]]

[[ 0.9022967 ]
 [ 0.46214396]
 [-0.57295817]
 [ 0.84693774]
 [ 0.01099153]]


In [ ]:
from sklearn.linear_model import LogisticRegression
#create an instance and fit the model 
logmodel2 = LogisticRegression()
logmodel2.fit(X_train7, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#predictions
predictions7 = logmodel2.predict(X_test7)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test,predictions7))  
print(classification_report(y_test,predictions7))  

[[15 20]
 [ 1 87]]
              precision    recall  f1-score   support

           0       0.94      0.43      0.59        35
           1       0.81      0.99      0.89        88

    accuracy                           0.83       123
   macro avg       0.88      0.71      0.74       123
weighted avg       0.85      0.83      0.81       123



**Observation: By using the LDA Method, we get the accuracy of 83%**

###**Decision: We will not use the LDA Method for reducing the features**